# https://cirrus-ci.org/guide/FreeBSD/#freebsd-virtual-machines
# https://cirrus-ci.org/guide/tips-and-tricks/#sharing-configuration-between-tasks
# https://stackoverflow.com/a/6651436

default: &DEFAULT
  script:
    - make clean
    - make -DDEBUG
    - make man
    - ./bsdhwmon -l
    - test -f bsdhwmon.8.txt

current_15_0_task:
  <<: *DEFAULT
  freebsd_instance:
    image_family: freebsd-15-0-snap

releng_14_0_task:
  <<: *DEFAULT
  freebsd_instance:
    image_family: freebsd-14-0

releng_13_2_task:
  <<: *DEFAULT
  freebsd_instance:
    image_family: freebsd-13-2
