releng_12_0_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  script:
    - make clean
    - make -DDEBUG
    - make man
    - ./bsdhwmon -l
    - test -f bsdhwmon.8.txt

releng_11_2_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  script:
    - make clean
    - make -DDEBUG
    - make man
    - ./bsdhwmon -l
    - test -f bsdhwmon.8.txt

releng_11_1_task:
  freebsd_instance:
    image: freebsd-11-1-release-amd64
  script:
    - make clean
    - make -DDEBUG
    - make man
    - ./bsdhwmon -l
    - test -f bsdhwmon.8.txt

releng_10_4_task:
  freebsd_instance:
    image: freebsd-10-4-release-amd64
  script:
    - make clean
    - make -DDEBUG
    - make man
    - ./bsdhwmon -l
    - test -f bsdhwmon.8.txt

